export const LIST_BY_ID_REQUESTED = 'DOCUMENTS/LIST_BY_ID/REQUESTED'
export const LIST_BY_ID_SUCCEEDED = 'DOCUMENTS/LIST_BY_ID/SUCCEEDED'
export const LIST_BY_ID_FAILED = 'DOCUMENTS/LIST_BY_ID/FAILED'
